### ISSUE TITLE
Zabbix Authentication

### ISSUE THREAD

**Issue by kgrvamsi** [abanichev/zabbix#2]
Hi @abanichev ,

I'm checking the authentication functions and i see that we initially do the login request and then run the call and i also see this documentation line above the login call

```
@doc """
  Authorizes in Zabbix API using `user` and `password` and updates session state with granted token.
```

So once the Authentication is done and token is created the Zabbix.Client will have the token saved untill we do that logout call and what would be a optimal timer for the session to have the token valid?

**Comment by abanichev** [comment]
> So once the Authentication is done and token is created the Zabbix.Client will have the token saved untill we do that logout call

Yes, token will be saved in `Zabbix.Client` process so you do not need to worry about passing it to every request. It will be automatically applied to all subsequent `Zabbix.API.call`'s

> what would be a optimal timer for the session to have the token valid

I'm not sure what timer are talking about? `Auto-logout` parameter in user configuration in Zabbix Frontend? Anyway... it depends. If you want to run your application for long time, you can set expiration timer to bigger value.

Also there is `user.checkAuthentication` method in Zabbix API that checks passed token and prolongs user session (by default) if it is valid. Under the hood `Zabbix.API.login(token)` function using this method to get you logged in by token instead of user/password. So you can save granted token somewhere to reuse it between application runs.
